### ISSUE TITLE
1.0.30001394 is missing css-unicode-bidi

### ISSUE THREAD

**Issue by usulix** [browserslist/caniuse-lite#100]
Is this intentional?

I am starting a new nuxt 3 app and had to drop back to 1.0.30001393

**Comment by ai** [comment]
We are repacking `caniuse-db`. Check does it have the file.

**Comment by SinHouse** [comment]
@ai, still missing in:
```
  "name": "caniuse-lite",
  "version": "1.0.30001394",
```

**Comment by usulix** [comment]
https://github.com/Fyrd/caniuse/commit/40a057c6a865d7b1587a5c8701edec84bc3de91c

**Comment by usulix** [comment]
I'll pop a notice / issue on the nuxt site.

**Comment by realgavinmartin** [comment]
<img width="721" alt="2022-09-11 at 19 32 23@2x" src="https://user-images.githubusercontent.com/47824008/189553575-1f52b6df-b1af-4719-bf84-327cc30ff07f.png">

**Comment by ai** [comment]
I am working on the fix.

If you want to support our work in the night to fix the bug, here is PostCSS & Autoprefixer open collective:
https://opencollective.com/postcss

**Comment by ctnelson1997** [comment]
For anyone looking, this impacts new projects created with `create-react-app`.

```
Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
Loading PostCSS "postcss-preset-env" plugin failed: Cannot find module 'caniuse-lite/data/features/css-unicode-bidi'
```

**Comment by ai** [comment]
I am fixing the issue in Autoprefixer right now. Don’t worry.

If you want to support our work in the night to fix the bug, here is PostCSS & Autoprefixer open collective:
https://opencollective.com/postcss

**Comment by tim-on-github** [comment]
Just started on a new `docusaurus` app and had issues with this also

As an aside - proper use of Semver would help in these situations. I'd like to encourage its use.

**Comment by realgavinmartin** [comment]
> 

Yep same thing with creating a new Angular app, glad it's being resolved promptly

**Comment by JasonFengGit** [comment]
Can moving back to 30001393 solve the problem?

**Comment by ai** [comment]
The fix was released in Autoprefixer 10.4.9.

If you want to support our work in the night to fix the bug, here is PostCSS & Autoprefixer open collective:
https://opencollective.com/postcss

**Comment by JasonFengGit** [comment]
I am sorry, what should we do from our ends?

**Comment by ZoranRavic** [comment]
> Can moving back to 30001393 solve the problem?

Yes, you could revert, but it seems that the fix is online already, you can update to it:

```
npx browserslist@latest --update-db
```

**Comment by ZoranRavic** [comment]
I just checked the latest version `1.0.30001396` and `css-unicode-bidi` is still missing.

**Comment by eglove** [comment]
Broken: 1.0.30001396

Last working version: 1.0.30001393

**Comment by lukeschunk** [comment]
if anyone got here in a create react app trying to update browserlist, re-running `npx browserslist@latest --update-db` should update to `1.0.30001397` which (to the above comment)
> works fine
